export const CALENDLY = "https://calendly.com/cbencorrec/first"
export const INSTAGRAM = "https://www.instagram.com/c_ben_correc/"
export const LINKEDIN = "https://www.linkedin.com/in/flo%C3%A9-gaubert-cbencorrec/"
export const EMAIL = "mailto:cbencorrec@gmail.com"
export const TEL = "tel:0683988242"